imports:
  - { resource: common.yml }
parameters:
  ps_accounts.environment: 'production'
  ps_accounts.accounts_api_url: 'https://accounts-api.distribution.prestashop.net/v1/'
  ps_accounts.accounts_ui_url: 'https://accounts.distribution.prestashop.net'
  ps_accounts.sso_api_url: 'https://auth.prestashop.com/api/v1/'
  ps_accounts.sso_account_url: 'https://auth.prestashop.com/login'
  ps_accounts.sso_resend_verification_email_url: 'https://auth.prestashop.com/account/send-verification-email'
  ps_accounts.billing_api_url: 'https://billing-api.distribution.prestashop.net/'
  ps_accounts.sentry_credentials: 'https://4c7f6c8dd5aa405b8401a35f5cf26ada@o298402.ingest.sentry.io/5354585'
  ps_accounts.segment_write_key: 'pEJGnRxw47CU01efFjMyl1S7YcxshLxl'
  ps_accounts.check_api_ssl_cert: true
  ps_accounts.verify_account_tokens: true
  ps_accounts.accounts_vue_cdn_url: 'https://unpkg.com/prestashop_accounts_vue_components@3/dist/psaccountsVue.umd.min.js'
  ps_accounts.accounts_cdn_url: 'https://unpkg.com/prestashop_accounts_vue_components@4/dist/psaccountsVue.umd.min.js'
  ps_accounts.svc_accounts_ui_url: 'https://accounts.psessentials.net'
  ps_accounts.oauth2_url_authorize: 'https://oauth.prestashop.com/oauth2/auth'
  ps_accounts.oauth2_url_access_token: 'https://oauth.prestashop.com/oauth2/token'
  ps_accounts.oauth2_url_resource_owner_details: 'https://oauth.prestashop.com/userinfo'
  ps_accounts.oauth2_url_session_logout: 'https://oauth.prestashop.com/oauth2/sessions/logout'
  ps_accounts.uri_help_center_en: "https://help-center.prestashop.com/en/articles/8087001455634-i-cannot-log-in-to-the-back-office-of-my-edition-shop-with-my-prestashop-account"
  ps_accounts.uri_help_center_fr: "https://help-center.prestashop.com/fr/articles/8087001455634-je-ne-peux-pas-me-connecter-au-back-office-de-ma-boutique-edition-avec-mon-compte-prestashop"
